# -*- coding: utf-8 -*-
"""Ejercicio 2.1_MetodoDeBiseccion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfiHFrAOaqRiILmWqJ5xOrbK1dL46qKG
"""

#Antonio Josue Rodriguez Falcon

import numpy as np
import matplotlib.pyplot as plt

# Definir la función g(x) para el método de punto fijo
def g(x):
    return (1 - x)**(1/3)

# Criterio de convergencia
def g_prime(x):
    return -(1/3) * (1 - x)**(-2/3)

# Error absoluto
def error_absoluto(x_new, x_old):
    return abs(x_new - x_old)

# Error relativo
def error_relativo(x_new, x_old):
    return abs((x_new - x_old) / x_new)

# Error cuadrático
def error_cuadratico(x_new, x_old):
    return (x_new - x_old)**2

# Método de punto fijo
def punto_fijo(x0, tol=1e-5, max_iter=100):
    iteraciones = []
    errores_abs = []
    errores_rel = []
    errores_cuad = []

    x_old = x0
    for i in range(max_iter):
        x_new = g(x_old)
        e_abs = error_absoluto(x_new, x_old)
        e_rel = error_relativo(x_new, x_old)
        e_cuad = error_cuadratico(x_new, x_old)

        iteraciones.append((i+1, x_new, e_abs, e_rel, e_cuad))
        errores_abs.append(e_abs)
        errores_rel.append(e_rel)
        errores_cuad.append(e_cuad)

        if e_abs < tol:
            break

        x_old = x_new

    return iteraciones, errores_abs, errores_rel, errores_cuad

# Parámetros iniciales
x0 = 0.5
iteraciones, errores_abs, errores_rel, errores_cuad = punto_fijo(x0)

# Imprimir tabla de iteraciones
print("Iteración | x_n      | Error absoluto | Error relativo | Error cuadrático")
print("-----------------------------------------------------------------------")
for it in iteraciones:
    print(f"{it[0]:9d} | {it[1]:.6f} | {it[2]:.6e} | {it[3]:.6e} | {it[4]:.6e}")

# Graficar la convergencia
x_vals = np.linspace(-1, 1, 100)
y_vals = g(x_vals)

plt.figure(figsize=(8, 5))
plt.plot(x_vals, y_vals, label=r"$g(x) = (1 - x)^{1/3}$", color="blue")
plt.plot(x_vals, x_vals, linestyle="dashed", color="red", label="y = x")

# Graficar iteraciones
x_points = [it[1] for it in iteraciones]
y_points = [g(x) for x in x_points]
plt.scatter(x_points, y_points, color="black", zorder=3)
plt.plot(x_points, y_points, linestyle="dotted", color="black", label="Iteraciones")

plt.xlabel("x")
plt.ylabel("g(x)")
plt.legend()
plt.grid(True)
plt.title("Método de Punto Fijo")
plt.savefig("punto_fijo_convergencia.png")
plt.show()

# Graficar errores
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(errores_abs) + 1), errores_abs, marker="o", label="Error absoluto")
plt.plot(range(1, len(errores_rel) + 1), errores_rel, marker="s", label="Error relativo")
plt.plot(range(1, len(errores_cuad) + 1), errores_cuad, marker="^", label="Error cuadrático")

plt.xlabel("Iteración")
plt.ylabel("Error")
plt.yscale("log")
plt.legend()
plt.grid(True)
plt.title("Evolución de los Errores")
plt.savefig("errores_punto_fijo.png")
plt.show()

# Antonio Josue Rodriguez Falcon
# Ejercicio 1

import numpy as np
import matplotlib.pyplot as plt

# Definir la función
def f(x):
    return x**3 - 4*x - 9

# Método de bisección
def biseccion(a, b, tol=1e-5, max_iter=100):
    if f(a) * f(b) >= 0:
        print("El método de bisección no es aplicable en este intervalo.")
        return None, None

    iteraciones = []
    errores = []

    for i in range(max_iter):
        c = (a + b) / 2
        iteraciones.append((i+1, c, f(c)))
        error = abs(b - a) / 2
        errores.append(error)

        if abs(f(c)) < tol or error < tol:
            return c, iteraciones, errores

        if f(c) * f(a) < 0:
            b = c
        else:
            a = c

    return c, iteraciones, errores

# Intervalo y tolerancia
a, b = 2, 3
tolerancia = 1e-5

# Llamar al método
raiz, iteraciones, errores = biseccion(a, b, tolerancia)

# Imprimir los resultados
print("Iteración | x_n      | f(x_n)")
print("--------------------------------")
for it in iteraciones:
    print(f"{it[0]:9d} | {it[1]:.6f} | {it[2]:.6e}")

print(f"\nAproximación de la raíz: {raiz:.6f}")

# Graficar la función con la raíz encontrada
x_vals = np.linspace(1, 4, 400)
y_vals = f(x_vals)

plt.figure(figsize=(8, 5))
plt.plot(x_vals, y_vals, label="f(x) = x^3 - 4x - 9", color="Red")
plt.axhline(0, color="black", linewidth=0.8, linestyle="dashed")
plt.axvline(raiz, color="blue", linestyle="dashed", label=f"Raíz aproximada: {raiz:.6f}")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.legend()
plt.grid(True)
plt.title("Método de Bisección - Convergencia")
plt.show()

# Graficar la evolución del error
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(errores) + 1), errores, marker="o", linestyle="-", color="Purple", label="Error")
plt.xlabel("Iteración")
plt.ylabel("Error")
plt.yscale("log")
plt.legend()
plt.grid(True)
plt.title("Evolución del Error en el Método de Bisección")
plt.show()

#Antonio Josue Rodriguez Falcon
#Ejercicio 2

import numpy as np
import matplotlib.pyplot as plt

# Definir la función
def f(x):
    return np.exp(-x) - x

# Método de bisección
def biseccion(a, b, tol=1e-5, max_iter=100):
    if f(a) * f(b) > 0:
        raise ValueError("El intervalo no contiene una raíz.")

    iteraciones = []
    errores = []
    fa = f(a)

    for i in range(max_iter):
        c = (a + b) / 2
        fc = f(c)

        iteraciones.append((i+1, c, fc))
        error = abs(b - a) / 2
        errores.append(error)

        if error < tol or abs(fc) < tol:
            break

        if fa * fc < 0:
            b = c
        else:
            a = c
            fa = fc

    return iteraciones, errores, c

# Definir intervalo y ejecutar el método
a, b = 0, 1
iteraciones, errores, raiz = biseccion(a, b)

# Imprimir resultados
print("Iteración | x_n      | f(x_n)")
print("--------------------------------")
for it in iteraciones:
    print(f"{it[0]:9d} | {it[1]:.6f} | {it[2]:.6e}")

print(f"\nRaíz aproximada: {raiz:.6f}")

# Graficar la función
x_vals = np.linspace(-0.2, 1.2, 400)
y_vals = f(x_vals)

plt.figure(figsize=(8, 5))
plt.plot(x_vals, y_vals, label=r"$f(x) = e^{-x} - x$", color="Purple")
plt.axhline(0, color='black', linestyle='dashed')
plt.axvline(raiz, color='blue', linestyle='dotted', label=f"Raíz ≈ {raiz:.6f}")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.legend()
plt.grid(True)
plt.title("Método de Bisección - Convergencia")
plt.show()

# Graficar la evolución del error
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(errores) + 1), errores, marker="o", linestyle="-", color="red", label="Error")
plt.xlabel("Iteración")
plt.ylabel("Error")
plt.yscale("log")
plt.legend()
plt.grid(True)
plt.title("Evolución del Error en el Método de Bisección")
plt.show()

#Antonio Josue Rodriguez Falcon
#Ejercicio 3

import numpy as np
import matplotlib.pyplot as plt

# Definir la función
def f(x):
    return np.cos(x) - x

# Método de bisección
def biseccion(a, b, tol=1e-5, max_iter=100):
    if f(a) * f(b) > 0:
        raise ValueError("El intervalo no contiene una raíz.")

    iteraciones = []
    errores = []
    fa = f(a)

    for i in range(max_iter):
        c = (a + b) / 2
        fc = f(c)

        iteraciones.append((i+1, c, fc))
        error = abs(b - a) / 2
        errores.append(error)

        if error < tol or abs(fc) < tol:
            break

        if fa * fc < 0:
            b = c
        else:
            a = c
            fa = fc

    return iteraciones, errores, c

# Definir intervalo y ejecutar el método
a, b = 0, 1
iteraciones, errores, raiz = biseccion(a, b)

# Imprimir resultados
print("Iteración | x_n      | f(x_n)")
print("--------------------------------")
for it in iteraciones:
    print(f"{it[0]:9d} | {it[1]:.6f} | {it[2]:.6e}")

print(f"\nRaíz aproximada: {raiz:.6f}")

# Graficar la función
x_vals = np.linspace(-0.2, 1.2, 400)
y_vals = f(x_vals)

plt.figure(figsize=(8, 5))
plt.plot(x_vals, y_vals, label=r"$f(x) = \cos(x) - x$", color="Black")
plt.axhline(0, color='black', linestyle='dashed')
plt.axvline(raiz, color='blue', linestyle='dotted', label=f"Raíz ≈ {raiz:.6f}")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.legend()
plt.grid(True)
plt.title("Método de Bisección - Convergencia")
plt.show()

# Graficar la evolución del error
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(errores) + 1), errores, marker="o", linestyle="-", color="black", label="Error")
plt.xlabel("Iteración")
plt.ylabel("Error")
plt.yscale("log")
plt.legend()
plt.grid(True)
plt.title("Evolución del Error en el Método de Bisección")
plt.show()